---
# Values here are the same across all environments
generic-service:
  nameOverride: prison-register
  serviceAccountName: hmpps-registers
  image:
    repository: ghcr.io/ministryofjustice/prison-register
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /prometheus {
          deny all;
          return 401;
        }
    tlsSecretName: prison-register-cert

  env:
    SERVER_PORT: 8080
    JAVA_OPTS: "-Xmx512m"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_SQS_USE_WEB_TOKEN: true
    PRODUCT_ID: 'DPS098'

  namespace_secrets:
    prison-register:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      HMPPS_AUTH_CLIENT_CLIENT_ID: "SYSTEM_CLIENT_ID"
      HMPPS_AUTH_CLIENT_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    prisons-rds-instance-output:
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
      SPRING_DATASOURCE_USERNAME: "database_username"
      SPRING_DATASOURCE_PASSWORD: "database_password"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
    sqs-hmpps-audit-secret:
      HMPPS_SQS_QUEUES_AUDIT_QUEUE_NAME: "sqs_queue_name"

generic-prometheus-alerts:
  targetApplication: prison-register
  alertSeverity: move-a-prisoner-alerts-nonprod
