---
# Values here are the same across all environments
generic-service:
  nameOverride: prison-register

  image:
    repository: quay.io/hmpps/prison-register
    tag: latest
    port: 8080

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        server_tokens off;
        location /prometheus {
          deny all;
          return 401;
        }
    tlsSecretName: prison-register-cert
    contextColour: green

  env:
    SERVER_PORT: 8080
    JAVA_OPTS: "-Xmx512m"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  namespace_secrets:
    prison-register:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      HMPPS_AUTH_CLIENT_CLIENT_ID: "SYSTEM_CLIENT_ID"
      HMPPS_AUTH_CLIENT_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    prisons-rds-instance-output:
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
      SPRING_DATASOURCE_USERNAME: "database_username"
      SPRING_DATASOURCE_PASSWORD: "database_password"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_TOPICS_DOMAINEVENTS_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
    sqs-hmpps-audit-secret:
      HMPPS_SQS_QUEUES_AUDIT_QUEUE_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_AUDIT_QUEUE_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_AUDIT_QUEUE_NAME: "sqs_queue_name"

generic-prometheus-alerts:
  targetApplication: prison-register
