version: "3"
services:
  localstack:
    image: localstack/localstack:0.14.5
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566-4597:4566-4597"
    environment:
      - SERVICES=sqs,sns
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
      - PORT_WEB_UI=${PORT_WEB_UI- }
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  hmpps:
