server.shutdown: immediate

oauth:
  endpoint.url: http://localhost:9090/auth

audit:
  endpoint.url: http://localhost:8182

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prison-register-db
    username: admin
    password: admin_password
  jpa:
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

hmpps-auth:
  client:
    client-id: prison-register-api-client
    client-secret: clientsecret
    access-token-uri: http://localhost:9090/auth/oauth/token
