server.shutdown: immediate

oauth:
  endpoint.url: http://localhost:9090/auth

aws:
  provider: localstack

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

hmpps.sqs:
  provider: localstack
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:hmpps_domain_events
