spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub
  datasource:
    url: jdbc:postgresql://localhost:5432/visit_scheduler
    username: visit_scheduler
    password: visit_scheduler

oauth:
  endpoint.url: http://localhost:8090/auth
