# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: quay.io/hmpps/prison-register
  tag: latest
  pullPolicy: Always
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: prison-register.hmpps.service.justice.gov.uk
      cert_secret: prison-register-cert
  path: /

env:
  JAVA_OPTS: "-Xmx512m"
  OAUTH_ENDPOINT_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
