generic-service:

  ingress:
    host: prison-register-preprod.hmpps.service.justice.gov.uk

  scheduledDowntime:
    enabled: true
    startup: '30 6 * * 1-5' # Start at 6:30am UTC Monday-Friday
    shutdown: '30 21 * * 1-5' # Stop at 9:30pm UTC Monday-Friday

  env:
    OAUTH_ENDPOINT_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    AUDIT_ENDPOINT_URL: "https://audit-api-preprod.hmpps.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
  rdsAlertsDatabases:
    cloud-platform-897c419584ae8631: 'prison register'
