# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
generic-service:
  ingress:
    host: prison-register.hmpps.service.justice.gov.uk
  env:
    OAUTH_ENDPOINT_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"

# determine which slack channel alerts are sent to, via the correct Alert Manager receiver
generic-prometheus-alerts:
  alertSeverity: digital-prison-service
