# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
generic-service:
  ingress:
    host: prison-register-preprod.hmpps.service.justice.gov.uk
  env:
    OAUTH_ENDPOINT_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    AUDIT_ENDPOINT_URL: "https://audit-api-preprod.hmpps.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
