INSERT INTO prison VALUES ('ALI', 'Albany (HMP)', false);
INSERT INTO prison VALUES ('AKI', 'Acklington (HMP)', false);
INSERT INTO prison VALUES ('KTI', 'Kennet (HMP)', true);
INSERT INTO prison VALUES ('HEI', 'HMP Hewell', true);
INSERT INTO prison VALUES ('ACI', 'Altcourse (HMP)', true);
INSERT INTO prison VALUES ('ASI', 'Ashfield (HMP)', true);
INSERT INTO prison VALUES ('AWI', 'Ashwell (HMP)', false);
INSERT INTO prison VALUES ('AGI', 'Askham Grange (HMP & YOI)', true);
INSERT INTO prison VALUES ('AYI', 'Aylesbury (HMP)', true);
INSERT INTO prison VALUES ('BFI', 'Bedford (HMP)', true);
INSERT INTO prison VALUES ('BAI', 'Belmarsh (HMP)', true);
INSERT INTO prison VALUES ('BMI', 'Birmingham (HMP)', true);
INSERT INTO prison VALUES ('BTI', 'Blakenhurst (HMP)', false);
INSERT INTO prison VALUES ('BHI', 'Blantyre House (HMP)', false);
INSERT INTO prison VALUES ('BDI', 'Blundeston (HMP)', false);
INSERT INTO prison VALUES ('BSI', 'Brinsford (HMP)', true);
INSERT INTO prison VALUES ('BLI', 'Bristol (HMP)', true);
INSERT INTO prison VALUES ('BXI', 'Brixton (HMP)', true);
INSERT INTO prison VALUES ('BKI', 'Brockhill (HMP & YOI)', false);
INSERT INTO prison VALUES ('BZI', 'Bronzefield (HMP)', true);
INSERT INTO prison VALUES ('BCI', 'Buckley Hall (HMP)', true);
INSERT INTO prison VALUES ('BNI', 'Bullingdon (HMP)', true);
INSERT INTO prison VALUES ('BUI', 'Bullwood Hall (HMP)', false);
INSERT INTO prison VALUES ('CHI', 'Camp Hill (HMP)', false);
INSERT INTO prison VALUES ('CYI', 'Canterbury (HMP)', false);
INSERT INTO prison VALUES ('CFI', 'Cardiff (HMP)', true);
INSERT INTO prison VALUES ('CSI', 'Castington (HMP & YOI)', false);
INSERT INTO prison VALUES ('CWI', 'Channings Wood (HMP)', true);
INSERT INTO prison VALUES ('CDI', 'Chelmsford (HMP)', true);
INSERT INTO prison VALUES ('CLI', 'Coldingley (HMP)', true);
INSERT INTO prison VALUES ('CKI', 'Cookham Wood (HMP)', true);
INSERT INTO prison VALUES ('DAI', 'Dartmoor (HMP)', true);
INSERT INTO prison VALUES ('DTI', 'Deerbolt (HMPYOI)', true);
INSERT INTO prison VALUES ('DNI', 'Doncaster (HMP)', true);
INSERT INTO prison VALUES ('DRI', 'Dorchester (HMP)', false);
INSERT INTO prison VALUES ('DGI', 'Dovegate (HMP)', true);
INSERT INTO prison VALUES ('DVI', 'Dover Immigration Removal Centre', false);
INSERT INTO prison VALUES ('DWI', 'Downview (HMP)', true);
INSERT INTO prison VALUES ('DHI', 'Drake Hall (HMP & YOI)', true);
INSERT INTO prison VALUES ('DMI', 'Durham (HMP)', true);
INSERT INTO prison VALUES ('ESI', 'East Sutton Park (HMP & YOI)', true);
INSERT INTO prison VALUES ('EWI', 'Eastwood Park (HMP)', true);
INSERT INTO prison VALUES ('NEI', 'Edmunds Hill (HMP)', false);
INSERT INTO prison VALUES ('EYI', 'Elmley (HMP)', true);
INSERT INTO prison VALUES ('EEI', 'Erlestoke (HMP)', true);
INSERT INTO prison VALUES ('EVI', 'Everthorpe (HMP)', false);
INSERT INTO prison VALUES ('EXI', 'Exeter (HMP)', true);
INSERT INTO prison VALUES ('FSI', 'Featherstone (HMP)', true);
INSERT INTO prison VALUES ('FMI', 'Feltham (HMP & YOI)', true);
INSERT INTO prison VALUES ('FDI', 'Ford (HMP)', true);
INSERT INTO prison VALUES ('FBI', 'Forest Bank (HMP & YOI)', true);
INSERT INTO prison VALUES ('FHI', 'Foston Hall (HMP)', true);
INSERT INTO prison VALUES ('FKI', 'Frankland (HMP)', true);
INSERT INTO prison VALUES ('FNI', 'Full Sutton (HMP)', true);
INSERT INTO prison VALUES ('GHI', 'Garth (HMP)', true);
INSERT INTO prison VALUES ('GTI', 'Gartree (HMP)', true);
INSERT INTO prison VALUES ('GPI', 'Glen Parva (HMPYOI & Rc)', false);
INSERT INTO prison VALUES ('GLI', 'Gloucester (HMP)', false);
INSERT INTO prison VALUES ('GNI', 'Grendon (HMP)', true);
INSERT INTO prison VALUES ('GMI', 'Guys Marsh (HMP)', true);
INSERT INTO prison VALUES ('HRI', 'Haslar Immigration Removal Centre', false);
INSERT INTO prison VALUES ('HVI', 'Haverigg (HMP)', true);
INSERT INTO prison VALUES ('HGI', 'Hewell Grange (HMP)', false);
INSERT INTO prison VALUES ('HOI', 'High Down (HMP)', true);
INSERT INTO prison VALUES ('HPI', 'Highpoint (HMP)', true);
INSERT INTO prison VALUES ('HII', 'Hindley (HMP & YOI)', true);
INSERT INTO prison VALUES ('HBI', 'Hollesley Bay (HMP)', true);
INSERT INTO prison VALUES ('HYI', 'Holloway (HMP)', false);
INSERT INTO prison VALUES ('HHI', 'Holme House (HMP)', true);
INSERT INTO prison VALUES ('HLI', 'Hull (HMP)', true);
INSERT INTO prison VALUES ('HCI', 'Huntercombe (HMP)', true);
INSERT INTO prison VALUES ('PTI', 'Kingston (HMP)', false);
INSERT INTO prison VALUES ('KMI', 'Kirkham (HMP)', true);
INSERT INTO prison VALUES ('KVI', 'Kirklevington Grange (HMP)', true);
INSERT INTO prison VALUES ('LAI', 'Lancaster Castle (HMP)', false);
INSERT INTO prison VALUES ('LFI', 'Lancaster Farms (HMP)', true);
INSERT INTO prison VALUES ('LMI', 'Latchmere House (HMP)', false);
INSERT INTO prison VALUES ('LEI', 'Leeds (HMP)', true);
INSERT INTO prison VALUES ('LCI', 'Leicester (HMP)', true);
INSERT INTO prison VALUES ('LWI', 'Lewes (HMP)', true);
INSERT INTO prison VALUES ('LYI', 'Leyhill (HMP)', true);
INSERT INTO prison VALUES ('LII', 'Lincoln (HMP)', true);
INSERT INTO prison VALUES ('LHI', 'Lindholme (HMP)', true);
INSERT INTO prison VALUES ('LTI', 'Littlehey (HMP)', true);
INSERT INTO prison VALUES ('LPI', 'Liverpool (HMP)', true);
INSERT INTO prison VALUES ('LLI', 'Long Lartin (HMP)', true);
INSERT INTO prison VALUES ('LNI', 'Low Newton (HMP)', true);
INSERT INTO prison VALUES ('LGI', 'Lowdham Grange (HMP)', true);
INSERT INTO prison VALUES ('MSI', 'Maidstone (HMP)', true);
INSERT INTO prison VALUES ('MRI', 'Manchester (HMP)', true);
INSERT INTO prison VALUES ('MDI', 'Moorland (HMP & YOI)', true);
INSERT INTO prison VALUES ('HDI', 'Hatfield (HMP & YOI)', true);
INSERT INTO prison VALUES ('MHI', 'Morton Hall Immigration Removal Centre', true);
INSERT INTO prison VALUES ('NHI', 'New Hall (HMP)', true);
INSERT INTO prison VALUES ('NSI', 'North Sea Camp (HMP)', true);
INSERT INTO prison VALUES ('NNI', 'Northallerton (HMP)', false);
INSERT INTO prison VALUES ('NWI', 'Norwich (HMP & YOI)', true);
INSERT INTO prison VALUES ('NMI', 'Nottingham (HMP)', true);
INSERT INTO prison VALUES ('ONI', 'Onley (HMP)', true);
INSERT INTO prison VALUES ('PRI', 'Parc (HMP)', true);
INSERT INTO prison VALUES ('PKI', 'Parkhurst (HMP)', false);
INSERT INTO prison VALUES ('PVI', 'Pentonville (HMP)', true);
INSERT INTO prison VALUES ('PDI', 'Portland (HMPYOI)', true);
INSERT INTO prison VALUES ('UPI', 'Prescoed (HMP & YOI)', true);
INSERT INTO prison VALUES ('PNI', 'Preston (HMP)', true);
INSERT INTO prison VALUES ('RNI', 'Ranby (HMP)', true);
INSERT INTO prison VALUES ('RDI', 'Reading (HMP & YOI)', false);
INSERT INTO prison VALUES ('RSI', 'Risley (HMP)', true);
INSERT INTO prison VALUES ('RCI', 'Rochester (HMP & YOI)', true);
INSERT INTO prison VALUES ('RHI', 'Rye Hill (HMP)', true);
INSERT INTO prison VALUES ('SDI', 'Send (HMP)', true);
INSERT INTO prison VALUES ('SMI', 'Shepton Mallet (HMP)', false);
INSERT INTO prison VALUES ('SYI', 'Shrewsbury (HMP)', false);
INSERT INTO prison VALUES ('SFI', 'Stafford (HMP)', true);
INSERT INTO prison VALUES ('EHI', 'Standford Hill (HMP)', true);
INSERT INTO prison VALUES ('SKI', 'Stocken (HMP)', true);
INSERT INTO prison VALUES ('SHI', 'Stoke Heath (HMPYOI)', true);
INSERT INTO prison VALUES ('STI', 'Styal (HMP & YOI)', true);
INSERT INTO prison VALUES ('SUI', 'Sudbury (HMP & YOI)', true);
INSERT INTO prison VALUES ('SLI', 'Swaleside (HMP)', true);
INSERT INTO prison VALUES ('SWI', 'Swansea (HMP)', true);
INSERT INTO prison VALUES ('SNI', 'Swinfen Hall (HMP)', true);
INSERT INTO prison VALUES ('MTI', 'The Mount (HMP)', true);
INSERT INTO prison VALUES ('VEI', 'The Verne (HMP)', true);
INSERT INTO prison VALUES ('WAI', 'The Weare (HMP)', false);
INSERT INTO prison VALUES ('TCI', 'Thorn Cross (HMPYOI)', true);
INSERT INTO prison VALUES ('UKI', 'Usk (HMP)', true);
INSERT INTO prison VALUES ('WDI', 'Wakefield (HMP)', true);
INSERT INTO prison VALUES ('WWI', 'Wandsworth (HMP)', true);
INSERT INTO prison VALUES ('WII', 'Warren Hill (HMP)', true);
INSERT INTO prison VALUES ('WLI', 'Wayland (HMP)', true);
INSERT INTO prison VALUES ('WEI', 'Wealstun (HMP)', true);
INSERT INTO prison VALUES ('WBI', 'Wellingborough (HMP)', false);
INSERT INTO prison VALUES ('WNI', 'Werrington (HMPYOI)', true);
INSERT INTO prison VALUES ('WYI', 'Wetherby (HMPYOI)', true);
INSERT INTO prison VALUES ('WTI', 'Whatton (HMP)', true);
INSERT INTO prison VALUES ('WRI', 'Whitemoor (HMP)', true);
INSERT INTO prison VALUES ('WCI', 'Winchester (HMP)', true);
INSERT INTO prison VALUES ('WOI', 'Wolds (HMP)', false);
INSERT INTO prison VALUES ('WHI', 'Woodhill (HMP)', true);
INSERT INTO prison VALUES ('WSI', 'Wormwood Scrubs (HMP)', true);
INSERT INTO prison VALUES ('WMI', 'Wymott (HMP)', true);
INSERT INTO prison VALUES ('FOI', 'Foreign Prison', false);
INSERT INTO prison VALUES ('PBI', 'Peterborough (HMP)', true);
INSERT INTO prison VALUES ('TAI', 'Thorp Arch (HMP)', false);
INSERT INTO prison VALUES ('RUI', 'Rudgate (HMP)', false);
INSERT INTO prison VALUES ('ANI', 'Aldington (HMP)', false);
INSERT INTO prison VALUES ('CEI', 'Cleland (HMP)', false);
INSERT INTO prison VALUES ('NOI', 'Northeye (HMP)', false);
INSERT INTO prison VALUES ('PCI', 'Pucklechurch (hmrc)', false);
INSERT INTO prison VALUES ('FII', 'Finnamore (hmYOI)', false);
INSERT INTO prison VALUES ('SPI', 'Spring Hill (HMP)', true);
INSERT INTO prison VALUES ('CPI', 'Campsfield House (hmYOI)', false);
INSERT INTO prison VALUES ('OXI', 'Oxford (HMP)', false);
INSERT INTO prison VALUES ('RLI', 'Rollestone (HMP)', false);
INSERT INTO prison VALUES ('CRI', 'Colchester (hmYOI)', false);
INSERT INTO prison VALUES ('ZZGHI', 'Ghost Holding Establishment', false);
INSERT INTO prison VALUES ('BRI', 'Bure (HMP)', true);
INSERT INTO prison VALUES ('ISI', 'Isis HMP/YOI', true);
INSERT INTO prison VALUES ('PFI', 'Peterborough Female HMP', true);
INSERT INTO prison VALUES ('OWI', 'Oakwood (HMP)', true);
INSERT INTO prison VALUES ('TSI', 'Thameside (HMP)', true);
INSERT INTO prison VALUES ('NLI', 'Northumberland (HMP)', true);
INSERT INTO prison VALUES ('IWI', 'Isle Of Wight (HMP)', true);
INSERT INTO prison VALUES ('HMI', 'Humber (HMP)', true);
INSERT INTO prison VALUES ('BWI', 'Berwyn (HMP)', true);
INSERT INTO prison VALUES ('MWI', 'Medway (stc)', true);