`INSERT INTO PRISON (PRISON_ID, NAME, ACTIVE) VALUES ('FEI', 'Fosse Way (HMP/YOI)', false);

INSERT INTO PRISON_TYPE (PRISON_ID, TYPE) VALUES ('FEI', 'HMP');
INSERT INTO PRISON_TYPE (PRISON_ID, TYPE) VALUES ('FEI', 'YOI');
