-- Missing YOI type
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('ACI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('BFI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('BAI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('BWI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('BLI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('BNI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('CFI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('DMI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('EEI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('EXI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('IWI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('KVI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('MRI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('NMI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('PRI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('PBI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('PFI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('PNI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('EHI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('SUI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('SWI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('TSI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('WWI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('WII', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('WSI', 'YOI');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('WMI', 'YOI');

-- Feltham is Youth Custody Service
UPDATE PRISON_TYPE SET TYPE = 'YOI' WHERE PRISON_ID = 'FMI' AND TYPE = 'HMP';
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('HHI', 'YOI');

-- Isis currently has duplicate YOI entries in PRISON_TYPE
DELETE FROM PRISON_TYPE WHERE PRISON_ID = 'ISI';
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('ISI', 'HMP');
INSERT INTO PRISON_TYPE(PRISON_ID, TYPE) VALUES ('ISI', 'YOI');

-- Removing Parc (HMYOI) as not present in master spreadsheet
DELETE FROM PRISON_TYPE WHERE PRISON_ID = 'PYI';
DELETE FROM ADDRESS WHERE PRISON_ID = 'PYI';
DELETE FROM OFFENDER_MANAGEMENT_UNIT WHERE PRISON_ID = 'PYI';
DELETE FROM PRISON_GP_PRACTICE WHERE PRISON_ID = 'PYI';
DELETE FROM PRISON WHERE PRISON_ID = 'PYI';

-- Wetherby is Youth Custody Service
DELETE FROM PRISON_TYPE WHERE PRISON_ID = 'WYI' AND TYPE = 'HMP';

-- Woodhill HMP only
DELETE FROM PRISON_TYPE WHERE PRISON_ID = 'WHI' AND TYPE = 'YOI';

